version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:management-alpine
        hostname: rabbitmq
        ports:
            - "15672:15672"  
            - "5672:5672"  
            - "5671:5671"  