version: '3.4'

services:

    #DATA  =========================================================================================================
    sql.data:
        image: mcr.microsoft.com/mssql/server:2019-latest
 
    nosql.data:
        image: mongo

    #EVENT BUS =========================================================================================================
    rabbitmq:
        image: rabbitmq:management-alpine
        hostname: ${PRICELY_EVENT_BUS_HOST}

    #LOGGING =========================================================================================================
    graylog.mongo:
        image: mongo

    graylog.elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0

    graylog:
        image: graylog/graylog:3.3.5-1

    #SERVICES =========================================================================================================
    items.api:
        image: ${REGISTRY:-pricely}/items.api:${PLATFORM:-linux}-${TAG:-latest}
        build:
            context: .
            dockerfile: Services/ItemService/ItemService.API/Dockerfile    
        depends_on:
            - sql.data
            - rabbitmq
      
    identity.api:
        image: ${REGISTRY:-pricely}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
        build:
            context: .
            dockerfile: Services/IdentityService/IdentityService.API/Dockerfile    
        depends_on:
            - sql.data
            - rabbitmq

    menu.api:
        image: ${REGISTRY:-pricely}/menu.api:${PLATFORM:-linux}-${TAG:-latest}
        build:
            context: .
            dockerfile: Services/MenuService/MenuService.API/Dockerfile    
        depends_on:
            - nosql.data
            - rabbitmq
