version: '3.4'

# The Production docker-compose file has to have the external/real IPs or DNS names for the services 
# The PRICELY_PROD_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like: 
#     PRICELY_PROD_EXTERNAL_DNS_NAME_OR_IP=192.168.88.248
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.
#
# IMPORTANT: Note that this compose file uses PRICELY_PROD_EXTERNAL_DNS_NAME_OR_IP instead of PRICELY_EXTERNAL_DNS_NAME_OR_IP

# Set ASPNETCORE_ENVIRONMENT= Development or Production, depending if you want to show up errors while testing. 
#
# You need to start it with the following CLI command:
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
      
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"    # Important: In a production environment your should remove the external port

  rabbitmq:
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port

  items.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${PRICELY_AZURE_REDIS_BASKET_DB:-Server=sql.data;Database=pricely_itemsdb;User Id=sa;Password=Pass@word}
      - EventBusConnection=${PRICELY_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${}
      - EventBusPassword=${PRICELY_SERVICE_BUS_PASSWORD}      
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}

    ports:
      - "80"   # The API Gateway redirects and access through the internal port (80). 

  items.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${PRICELY_AZURE_REDIS_BASKET_DB:-Server=sql.data;Database=pricely_itemsdb;User Id=sa;Password=Pass@word}
      - EventBusConnection=${PRICELY_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${}
      - EventBusPassword=${PRICELY_SERVICE_BUS_PASSWORD}      
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}

    ports:
      - "80"   # The API Gateway redirects and access through the internal port (80). 

