name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-menu-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./Pricely/Services/MenuService/MenuService.API/MenuService.API.csproj
    - name: Build Menu API
      run: dotnet build ./Pricely/Services/MenuService/MenuService.API/MenuService.API.csproj --configuration Release --no-restore

