name: Build projects

# trigger if any branch is pushed or pull request is open 
on: [push, pull_request]

# build all service code
jobs:

  build-menu-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./Pricely/Services/MenuService/MenuService.API/MenuService.API.csproj
    - name: Build Menu API
      run: dotnet build ./Pricely/Services/MenuService/MenuService.API/MenuService.API.csproj --configuration Release --no-restore
  
  build-identity-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./Pricely/Services/IdentityService/IdentityService.API/IdentityService.API.csproj
    - name: Build Menu API
      run: dotnet build ./Pricely/Services/IdentityService/IdentityService.API/IdentityService.API.csproj --configuration Release --no-restore
        
  build-item-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./Pricely/Services/ItemService/ItemService.API/ItemService.API.csproj
    - name: Build Menu API
      run: dotnet build ./Pricely/Services/ItemService/ItemService.API/ItemService.API.csproj --configuration Release --no-restore


